---

# - name: Create EC2 instances
#   ec2:
#     key_name: "{{ aws_ec2_key_name }}"
#     group: "{{ aws_ec2_sg_default_name }}"
#     instance_type: "{{ aws_ec2_instance_type }}"
#     image: "{{ ec2_ami_latest.image_id }}"
#     count: "{{ aws_ec2_instance_count }}"
#     wait: "{{ aws_ec2_instance_wait }}"
#     wait_timeout: "{{ aws_ec2_instance_wait_timeout }}"
#     volumes: "{{ aws_ec2_instance_volumes }}"
#     vpc_subnet_id: "{{ vpc_subnet_info.subnet.id }}"
#     instance_tags: "{{ aws_tags_default | combine ( aws_ec2_instance_tags ) }}"
#     assign_public_ip: "{{ aws_ec2_instance_public_ip }}"


- name: Create EC2 instances
  ec2_instance:
    key_name: "{{ aws_ec2_key_name }}"
    security_group: "{{ aws_ec2_sg_default_name }}"
    instance_type: "{{ aws_ec2_instance_type }}"
    image_id: "{{ ec2_ami_latest.image_id }}"
    count: "{{ aws_ec2_instance_count }}"
    wait: "{{ aws_ec2_instance_wait }}"
    wait_timeout: "{{ aws_ec2_instance_wait_timeout }}"
    volumes: "{{ aws_ec2_instance_volumes }}"
    vpc_subnet_id: "{{ vpc_subnet_info.subnet.id }}"
    tags: "{{ aws_tags_default | combine ( aws_ec2_instance_tags ) }}"
    network:
      assign_public_ip: "{{ aws_ec2_instance_public_ip }}"
